server:
  servlet:
    context-path: /redis
  port: 9008
spring:
  application:
    name: redission

  redis:
    # redission file 配置方式，可以注释 spring boot 默认的配置方式
#    host: 127.0.0.1
#    port: 6379
#    password: magebyte
#    ssl: false
    redisson:
      file: classpath:redisson-config.yaml

